### ISSUE TITLE
Add filter option to GUI

### ISSUE THREAD

**Issue by davve94** [lol2kpe/EDA397_Team3#20]

**Comment by jonagran** [comment]
Added a filter icon to the toolbar which responds to touch. Two things: Should the filter options be displayed as an AlertDialog (a small window is displayed with options), or as a separate Activity (a fullscreen option)? And how would you save filter options? I imagine a user opening the filter, selecting whatever the user wants to filter out, closing the filter and see the results on the map based on the chosen filter options, and if the user then reopens the filter, those options would still be selected (so the user doesn't have to rechose options everytime he/she opens the filter).

Completed with 0a59729310e10c14efbb00fd1f7b5e89076dee77

**Comment by jonagran** [comment]
The inital project comes with an added app bar. Currently, this app bar is being overwritten and replaced with a custom toolbar. This is apparently recommended as it allows for more customization with the app bar down the road.

**Comment by jonagran** [comment]
Okey, a working filter icon has been added to the created toolbar. Clicking the icon opens an AlertDialog with temporary filter options.

Functionality which needs to be added:
- Actual and relevant filter options
- The filter has real functionality (sending database pull requests based on chosen filter options, for example?)
- The filter "saves" chosen filter options (so the chosen options stays selected after the user closes the filter dialog, this might not be entirely necessary this sprint...)
