### ISSUE TITLE
Add function for Sending requests to database 

### ISSUE THREAD

**Issue by davve94** [lol2kpe/EDA397_Team3#23]

**Comment by lol2kpe** [comment]
This should be a function that calls the JSON/GSON-parser/requester #19, and handles the object(s) received from there.

**Comment by nandhujit** [comment]
e064f8c -   JSON parser  code, in my system i had error due to database connectivity  but its correct , check to it

**Comment by nandhujit** [comment]
the result function gets and can be displayed in text view, in that case separate list view must be created

**Comment by lol2kpe** [comment]
Sry about that, I experimented with the server a bit earlier :). There is not really any need to create a json parser here. The thought was to get all relevant objects from the database and parse them into java/android objects (#30), and later populate the map from that internal list. This task should not create a view of anything, but should only be some methods to call a parser (which is to be created in issue #19, as mentioned before) and create objects (Hotel object class created in #30) in the app, and adding them to a list (hotelsModel or something). The list is then accessed from the map-view when populating the map. 
To put it short, this task should say "hi parser, i want all objects!", and then create a list of hotel objects from the response... and of course some error handling if necessary.
