### ISSUE TITLE
Create/start database server

### ISSUE THREAD

**Issue by lol2kpe** [lol2kpe/EDA397_Team3#26]

**Comment by nandhujit** [comment]
what kind of database server u goona do ?

mysql server ?

**Comment by lol2kpe** [comment]
It will be a SQLite-server using rails for web-interface, creating JSON/GSON-objects which are then connected to with Volley #18, fetched and parsed using a JSON/GSON-parser module in the app #19.

**Comment by lol2kpe** [comment]
Fixed with commit d9f984ede6a61d9ec0dff35d8623c8773bce9f60
