### ISSUE TITLE
Create database contents

### ISSUE THREAD

**Issue by lol2kpe** [lol2kpe/EDA397_Team3#27]
Depends on
- #26 

Should contain
- Name
- Type
- Latitude
- Longitude
- Rating
- Comments (Deleted)
- Opening hours
- Address (Entity)
- Phone Number

**Comment by miguelascifo** [comment]
[Database_creation.txt](https://github.com/lol2kpe/EDA397_Team3/files/893004/Database_creation.txt)

Tables for database defined.

**Comment by nandhujit** [comment]
reference commit 5ee2fa7
